// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrfmbrwsjrhlymtkvmtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZm1icndzanJobHltdGt2bXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTIxMjQsImV4cCI6MjA3MTQ4ODEyNH0.jaYOj7H4gtfOeMePlwp0DUs_gPIePG8vwGCGurrub-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});